import java.io.Console;

public class RapGenerator {

  public static void main(String[] args) {
    Console console = System.console();

    String name = console.readLine("What is your rap name?   ");
    String groupOfFriends = console.readLine("Enter a name for a group of friends (i.e peeps, homies)   ");
    String adjectiveOne = console.readLine("Enter a good adjective of the highest order (bestest, coolest)   ");
    String adjectiveTwo = console.readLine("Enter a good adjective that is superior (better, cooler)   ");
    //initializing variables for use inside the loop
    int age = 0;
    Boolean isValidAge;
    //looping if input is invalid integer for age
    do {
      String ageAsString = console.readLine("Enter your age in years   ");
      try {
        //if this code is executed input is a valid integer and the loop finishes
        age = Integer.parseInt(ageAsString);
        isValidAge = true;
      } catch (NumberFormatException e) {
        //if the code in the try block isn't executed this code will be and the loop continues
        System.out.println("Input is not a valid integer age  \n");
        isValidAge = false;
      }
    } while (!isValidAge);
    //initializing the variable ageInWeeks and parsing it the age so it can be printed straight away
    String ageInWeeks = String.valueOf(age * 52);
    String hometown = console.readLine("Enter your hometown   ");
    String verbOne = console.readLine("Enter a verb ending in ING   ");
    String verbTwo = console.readLine("Enter a verb ending in ING   ");
    String verbThree = console.readLine("Enter a verb ending in ING   ");
    String favouritePerson = console.readLine("Enter your favourite person, living or dead famous or not   ");
    String adjectiveThree = console.readLine("Enter an adjective   ");
    //initializing variables for use in the loop
    String gender;
    Boolean isValidGender;
    //looping if input is invalid for gender variable (anything other than M,m,F,f will cause it to loop)
    do {
      gender = console.readLine("Enter your gender (m/f)   ");
      isValidGender = (gender.equalsIgnoreCase("m") || gender.equalsIgnoreCase("f"));
      if (!isValidGender) {
        console.printf("You need to enter m or f\n");
      }
    } while (!isValidGender);
    //initializing gender variables
    String genderOptionOne;
    String genderOptionTwo;
    String genderOptionThree;
    //if statement to set variables depending on the gender input
    if (gender.equalsIgnoreCase("m")) {
      genderOptionOne = "rude dude";
      genderOptionTwo = "He's";
      genderOptionThree = "guy";
    } else {
      genderOptionOne = "cool chick";
      genderOptionTwo = "She's";
      genderOptionThree = "girl";
    }
    //rap output
    console.printf("Your rap:  \n------------------\n");
    console.printf("Now listen up %s I got the word\n", groupOfFriends);
    console.printf("It's that %s %s haven't you heard?\n", genderOptionOne, name);
    console.printf("%s the %s, illest, take a look around\n", genderOptionTwo, adjectiveOne);
    console.printf("You won't find a %s %s out there, that's the true sound.\n------------------\n", adjectiveTwo, genderOptionThree);
    console.printf("My origin is deep, it's been %s weeks\n", ageInWeeks);
    console.printf("In the backstreets of %s, learnt to sneak\n", hometown);
    console.printf("%s, %s, %s, it's what I did\n", verbOne, verbTwo, verbThree);
    console.printf("But now i'm chilling with %s, no longer a kid\n------------------\n", favouritePerson);
    console.printf("My rap skills are pretty %s, huh?\n", adjectiveThree);
    console.printf("Promise it wasn't generated by a comput-erh\n");
    console.printf("I hope this script ran smooth, without a bug\n");
    console.printf("This is the end of the rap. Turn it off. Unplug.\n------------------\n");
  }
}
